config/routes.rb
Rails.application.routes.draw do
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Noaidi::DSL
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    Noaidi.match find_post(params[:id]), {
      [:ok, Post] => ->(post) { render locals: { post: post } },
      [:not_found, Array] => ->(posts) { render :not_found }
    }
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    Noaidi.match save_post(@post), {
      [:ok, Post] => ->(post) { redirect_to post, notice: 'Post successfully created' },
      [:invalid, any] => ->(validation_errors) { render :new },
      [:error, StandardError] => ->(error) { render :error_500, error: error }
    }
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    Noaidi.match save_post(@post), {
      [:ok, Post] => ->(post) { redirect_to post, notice: 'Post successfully updated' },
      [:invalid, any] => ->(validation_errors) { render :edit },
      [:error, StandardError] => ->(error) { render :error_500, error: error }
    }
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :author)
    end

    def save_post(post)
      if !post.valid?
        return [:invalid, @post.errors]
      end

      begin
        post.save!
        [:ok, post]
      rescue StandardError => e
        [:error, e]
      end
    end

    def find_post(id)
      post = Post.find_by(id: id)
      if post
        [:ok, post]
      else
        [:not_found, other_posts(id)]
      end
    end

    def other_posts(_id)
      Post.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoaidiRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.author %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= post.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= post.author %>
</p>

<%= link_to 'Edit', edit_post_path(post) %> |
<%= link_to 'Back', posts_path %>